update test mock reference
openware/irix pull request #10
Opened 2021-05-06 00:33 UTC by mgufrone

- some mock test reference are invalid or non existence in test
- update test runner (excluding huobi for now as the test hitting directly API but the test is outdated)

2021-05-07 11:20 UTC, al3rez requested changes

2021-05-07 11:20 UTC, al3rez commented on config/config.go
> -	}
is this intentded?

2021-05-07 11:20 UTC, al3rez commented on bittrex/bittrex_test.go
> +	if resp, err := b.GetFee(feeBuilder); resp != float64(0.00030) || err != nil {
please use a constant and name it, idk what is this

2021-05-07 11:20 UTC, al3rez commented on run_tests.sh
> +	cd $ROOT_DIR
i think we should keep go vert ./...

2021-05-07 11:29 UTC, mgufrone commented on config/config.go
> -	}
yep, intended for now

2021-05-07 13:00 UTC, al3rez approved these changes

2021-05-08 08:04 UTC, mod approved these changes

2021-05-08 08:04 UTC, merged